name: CI - PREPROD
on: 
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2

      - name: Export environment variables
        env: 
          GAE_PROJECT_ID: "${{ secrets.GAE_PROJECT_ID }}"
        run: | 
          echo GAE_PROJECT_ID="$GAE_PROJECT_ID" > ./.env
          composer install --no-interaction
      